title: Awakened PoE Trade
description: >-
  App for price-checking items in Path of Exile
app_version: 2.10.1
google_site_verification: R0xdvBEYFTxfn0RxHhquiA6tBgvshYv3ODk-oNSuq4g

markdown: kramdown
plugins:
  - jekyll-seo-tag
